# Generated by Django 2.1.2 on 2018-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_list', '0002_auto_20181118_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.TextField(),
        ),
    ]
