# Generated by Django 2.1.2 on 2018-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_list', '0003_auto_20181118_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
